### ISSUE TITLE
Tensorflow version?

### ISSUE THREAD

**Issue by maksimovkonstantin** [bermanmaxim/LovaszSoftmax#1]
Hi! 
Do you have tensorflow version? Because I have limited experience with PyTorch and I am stuck a little in reimplementation in tensorflow(((

**Comment by bermanmaxim** [comment]
Hi Maksimov,
I think we should have one version in Tensorflow soon but I can't promise you an ETA. I will update the repo when we do.
Cheers

**Comment by maksimovkonstantin** [comment]
@bermanmaxim that's great!

**Comment by bermanmaxim** [comment]
The TensorFlow version has been added.
