### ISSUE TITLE
Labels should be only {-1,1} in case of binary segmentation?

### ISSUE THREAD

**Issue by SorourMo** [bermanmaxim/LovaszSoftmax#10]
Hi there,

Thanks for sharing the code of this fantastic job. Congratulations on your CVPR paper! I have a question about the labels in the ground-truths. The gt labels should be {-1,1} (-1:background, 1:foreground) and for instance {0,1} (0:background, 1:foreground) doesn't work properly, right?

**Comment by bermanmaxim** [comment]
Hi, thanks! For the binary version it expects 0/1 masks, as seen e.g. [in this code comment](https://github.com/bermanmaxim/LovaszSoftmax/blob/master/pytorch/lovasz_losses.py#L98).

**Comment by SorourMo** [comment]
Perfect. Thanks

**Comment by kzh2ang** [comment]
Hi there,
Tanks for sharing the code of this fantastis job.  I meet the error using the lovasz_hinge function. Do you know what's wrong with it ?
An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

**Comment by bermanmaxim** [comment]
@kangzhang0709 what framework are you using?

**Comment by bermanmaxim** [comment]
@kangzhang0709 closing this issue, please open another one with more details about your problem (e.g. framework used)
