### ISSUE TITLE
What if i need to use weighted LovaszSoftmax.

### ISSUE THREAD

**Issue by Bonsen** [bermanmaxim/LovaszSoftmax#13]
What should I set?

**Comment by bermanmaxim** [comment]
In [lovasz_losses.py, line 188](https://github.com/bermanmaxim/LovaszSoftmax/blob/bd7e017173692b9824423e3b288b651ed526fc50/pytorch/lovasz_losses.py#L188), there is a mean between the C different classes. You can replace this by a weighted mean if you want to favor some of the classes.

**Comment by Bonsen** [comment]
Hi @bermanmaxim, 
I will try, thanks!
