### ISSUE TITLE
"name 'ifilterfalse' is not defined" in Python3

### ISSUE THREAD

**Issue by mxwell** [bermanmaxim/LovaszSoftmax#15]
Hi,
I've tried to run PyTorch implementation in Python 3.6 and got the error:

```
    226     l = iter(l)
    227     if ignore_nan:
--> 228         l = ifilterfalse(isnan, l)
    229     try:
    230         n = 1

NameError: name 'ifilterfalse' is not defined
```

I think the function needs to be aliased after import in Python 3 like this:

```
from itertools import filterfalse as filterfalse
```

**Comment by bermanmaxim** [comment]
I suppose you meant `from itertools import filterfalse as ifilterfalse`. That is correct. I'm open to a PR if you want to send one. Cheers, Maxim

**Comment by mdsalnikov** [comment]
https://github.com/bermanmaxim/LovaszSoftmax/pull/16
PR for solving this problem.

**Comment by bermanmaxim** [comment]
Thanks!
