### ISSUE TITLE
whats the difference with dice ?

### ISSUE THREAD

**Issue by argman** [bermanmaxim/LovaszSoftmax#17]
Thanks for this great work, but i canno understand, I think dice is also kind of optimizing iou, so whats the difference ?

**Comment by bermanmaxim** [comment]
Dice is also a measure of performance based on discrete predictions. I think you are referring to "soft-Dice", often used to optimize dice. In practice we found that these naïve continuous versions of the discrete loss perform worse than our surrogate.
