### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by alexander-rakhlin** [bermanmaxim/LovaszSoftmax#2]
Hi,
Thank you for your work.

I believe there is error here

https://github.com/bermanmaxim/LovaszSoftmax/blob/6309c68a2276ada25ebf04692575bce937460f1a/lovasz_losses.py#L26

should be
`jaccard[1:p] = jaccard[1:p] - jaccard[:p-1]`

**Comment by bermanmaxim** [comment]
Hi Alexander,

For pytorch tensors, pytorch Variables, as for python lists, these two are equivalent, since `jaccard` has length p in this case.

Did you observe something to the contrary in some version of pytorch/python?

**Comment by alexander-rakhlin** [comment]
Ah, sorry, I did not notice it has length of p. No, I did not, this was a formal consideration

**Comment by bermanmaxim** [comment]
No problem, thanks for your interest.
